# -*- mode: python -*-
# Spec file for compiling the code to an executable for windows

block_cipher = pyi_crypto.PyiBlockCipher(key='******')


a = Analysis(['Frontend_no_consolev2.py'],
             pathex=['C:\\Users\\u\\Desktop\\PACOM\\icon'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
			 
a.datas += [('about-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\about-icon.gif', 'DATA'),
            ('add-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\add-icon.gif', 'DATA'),
			('add-symbol.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\add-symbol.gif', 'DATA'),
			('ask-icon.png','C:\\Users\\u\\Desktop\\PACOM\\icon\\ask-icon.png', 'DATA'),
            ('back-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\back-icon.gif', 'DATA'),
			('back-icon2.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\back-icon2.gif', 'DATA'),
			('bulb-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\bulb-icon.gif', 'DATA'),
            ('cancel-icon.png','C:\\Users\\u\\Desktop\\PACOM\\icon\\cancel-icon.png', 'DATA'),
			('check-icon.png','C:\\Users\\u\\Desktop\\PACOM\\icon\\check-icon.png', 'DATA'),
			('checkmark-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\checkmark-icon.gif', 'DATA'),
			('cross-icon2.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\cross-icon2.gif', 'DATA'),
            ('delete-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\delete-icon.gif', 'DATA'),
            ('devices-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\devices-icon.gif', 'DATA'),
			('error-icon.png','C:\\Users\\u\\Desktop\\PACOM\\icon\\error-icon.png', 'DATA'),
			('find-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\find-icon.gif', 'DATA'),
			('home-icon1.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\home-icon1.gif', 'DATA'),
            ('home-icon2.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\home-icon2.gif', 'DATA'),			
            ('info-icon2.png','C:\\Users\\u\\Desktop\\PACOM\\icon\\info-icon2.png', 'DATA'),
			('ip-icon1.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\ip-icon1.gif', 'DATA'),
            ('ip-icon2.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\ip-icon2.gif', 'DATA'),
            ('ip-icon3.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\ip-icon3.gif', 'DATA'),
			('package-icon1.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\package-icon1.gif', 'DATA'),
            ('package-icon2.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\package-icon2.gif', 'DATA'),
            ('paul-icon1.ico','C:\\Users\\u\\Desktop\\PACOM\\icon\\paul-icon1.ico', 'DATA'),
            ('quit-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\quit-icon.gif', 'DATA'),
            ('search-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\search-icon.gif', 'DATA'),
            ('settings-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\settings-icon.gif', 'DATA'),			
            ('terminal-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\terminal-icon.gif', 'DATA'),
			('traffic-icon.gif','C:\\Users\\u\\Desktop\\PACOM\\icon\\traffic-icon.gif', 'DATA'),
			('warning-icon.png','C:\\Users\\u\\Desktop\\PACOM\\icon\\warning-icon.png', 'DATA')]
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='BasondoleTools',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True , icon='C:\\Users\\u\\Desktop\\PACOM\\icon\\paul-icon1.ico')
